import './globals.css'
import type { Metadata } from 'next'
import { Inter, Playfair } from 'next/font/google'
import Navbar from './component/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white min-h-screen max-w-full'>
        <header className='flex items-center p-4 gap-4'>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  )
}
